apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: simple-cr
spec:
  channel: dev/dev
  name: sample-cr-foo
  placement:
    local: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: simple-crd
spec:
  channel: dev/dev
  name: sample-crd
  placement:
    local: false
