apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-operators
rules:
- apiGroups:
  - 'app.ibm.com'
  resources:
  - 'placementrules'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 'app.ibm.com'
  resources:
  - 'deployables'
  verbs:
  - '*'
- apiGroups:
  - 'clusterregistry.k8s.io'
  resources:
  - 'clusters'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - 'pods'
  - 'configmaps'
  verbs:
  - get
  - create
