apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-operators-deployable
  labels:
    name: multicluster-operators-deployable
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-operators-deployable
  template:
    metadata:
      labels:
        name: multicluster-operators-deployable
    spec:
      serviceAccountName: multicluster-operators
      containers:
        - name: multicluster-operators-deployable
          # Replace this with the built image name
          image: quay.io/multiclusterlab/multicluster-operators-deployable
          command:
          - multicluster-operators-deployable
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicluster-operators-deployable"
