kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-operators
subjects:
- kind: ServiceAccount
  name: multicluster-operators
roleRef:
  kind: Role
  name: multicluster-operators
  apiGroup: rbac.authorization.k8s.io
