--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata: 
  name: payload-cfg-namespace-channel
  annotations: 
    app.ibm.com/is-local-deployable: "false"
  namespace: default
spec: 
  channels: 
  - ns
  template: 
    apiVersion: v1
    data: 
      database: mongodb
    kind: ConfigMap
    metadata: 
      name: cfg-from-ch-qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ns
  namespace: ch-ns
spec:
  type: Namespace
  pathname: ch-ns
  sourceNamespaces:
    - default
