kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators
subjects:
- kind: ServiceAccount
  name: multicloud-operators
  namespace: default
roleRef:
  kind: Role
  name: multicloud-operators
  apiGroup: rbac.authorization.k8s.io
