apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "false"
    apps.open-cluster-management.io/rollingupdate-maxunavaialble: "50"
    apps.open-cluster-management.io/rollingupdate-target: "sub-orig-target-deployable"
  name: sub-orig-deployable
  namespace: default
spec:
  placement:
      clusterSelector: {}
  template:
    apiVersion: apps.open-cluster-management.io/v1
    kind: Subscription
    metadata:
      labels:
        app: app111
      name: sub-orig
      namespace: default
    spec:
      channel: dev1/dev1
      packageFilter:
        version: =1.2.3
      placement:
        local: true
    status:
      lastUpdateTime: null
