apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: dev-helmrepo
  namespace: dev
spec:
    type: HelmRepo
    pathname: http://kubernetes-charts.storage.googleapis.com/
    insecureSkipVerify: true
