apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: simple
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
  placement:
    local: false
  packageOverrides:
  - packageName: nginx-ingress
    packageAlias: nginx-ingress-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 3