apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/rollingupdate-target: version-configmap
    apps.open-cluster-management.io/is-local-deployable: "false"
  name: rollingupdate-configmap
  namespace: default
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: default
    data:
      purpose: for test
  placement:
    clusterSelector: {}
