apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-mongodb-subscription
  annotations:
    apps.open-cluster-management.io/git-path: stable/ibm-mongodb-dev
#    apps.open-cluster-management.io/git-branch: branch1
spec:
  channel: ibmcharts/ibm-charts-git
  name: ibm-mongodb-dev
  placement:
    local: false
  packageOverrides:
  - packageName: ibm-mongodb-dev
    packageOverrides:
    - path: spec
      value:
        persistence:
          enabled: false
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            cpu: 200m
            memory: 500Mi