
os:
  - linux

language: go
go:
  - "1.15"

services:
  - docker

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "uFxxwoVBq3FVEhQGXhHB7AR+Dh5oLAfJ08i3k4AfnARdPQJkfXj4i3ar26CqmHpmCY37NN1slodVPHA7/SXkXrL2EVba5Ge5EFXAdQ5tfTkveYCFTopX/cary0rvWkgO41f1lBj7Y5MKfTXNqRr0kw8X4bsoHcKpYf8IAHTg4bU2YHQB+re7e1AQIvMh63Ye364U6hZTFuRnm0jXjP+mNmWVgSxQOEU5AcrYFHU3C4iOrsoScigTRkEBKMi7lGIThY3GTfpXeyxlNoGMTTh4X8STHIxwdSDuh/uVe4M/za8GjBjNVmwn7CbdZiVe5I8tHofV9PZCSYHjOZJLNqCIedko59P1kAuwAQxS75wr0FRXXdaa8p6fp0F5neWXvtvWHchmREsU2ZRtMa4HY0yQmK2Or8QKJPxm0gzjHqZ0cGF5r4ugmO6J7h8tydeb88a4kySb1oD2nzlSO8O+7dM21ST9DBGlYNxTwFgckIZJWQjmQ+YHhM9I4ILZSGXQSZSpmOhWII2JCWz7rnjGkSuiixRVJW1V9bSkTJejYuM4IVH0sM5m9MdyEOAC+4qdovSgcXRj4ttDfCQKfutA28IcHy2KGGLH91ED9UCI3e0OqP1lp14axEfkcB9U9wMV2rNNjarUkre14d3ucps6RqMdD8oezDWT2gAbCaC/4XQqK74="

env:
  global:
    # Required
    - OS=linux

    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/build/deploy-to-cluster.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

# define stages
stages:
  - lint
  - build
  - unit-test
  - test-e2e
  - publish

jobs:
  include:
    - stage: lint
      name: "Run code lint"
      if: type = pull_request
      script:
        - bash ${TRAVIS_BUILD_DIR}/build/run-code-lint.sh

    - stage: build
      name: "Build the image and run unit tests"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make init
          make component/build
          make component/push
          make security/scans
          make build-latest-community-operator
  
    - stage: unit-test
      name: "Run unit test"
      # if: type = pull_request
      script:
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.
        - make init
        - make component/test/unit
        - make sonar/go
  
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      #      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make init
          make component/pull
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - |
          make init
          make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
          make release-community-operator
